language: python
sudo: required

services:
  - docker

python:
  - "3.6"

git:
  submodules: false

stages:
  - before_install
  - install
  - name: after_success
    if: branch = master

before_install:
  - echo -e "machine github.com\n  login $GIT_USER\n  password $GIT_PASS" >> ~/.netrc
  - echo "Written git user to config file"
  - git submodule update --init --recursive
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

install:
  - docker build -t $DOCKER_PUB_ORG/fever-baselines .
  - docker tag $DOCKER_PUB_ORG/fever-baselines:build-$TRAVIS_BUILD_NUMBER
  - docker push

script:
  - echo "Done"

after_success:
  - $DOCKER_PUB_ORG/fever:latest
  - docker push