language: python
git:
	submodules: false
before_install:
	- echo -e "machine github.com\n  login $GIT_USER\n  password $GIT_PASS" >> ~/.netrc
	- echo "$GIT_USER"
	- git submodule update --init --recursive
