language: python
sudo: required

services:
  - docker

python:
  - "3.6"

git:
  submodules: false

before_install:
  - echo -e "machine github.com\n  login $GIT_USER\n  password $GIT_PASS" >> ~/.netrc
  - echo "Written git user to config file"
  - git submodule update --init --recursive

install:
  - docker build -t fever .
